class trystack::params {
  $admin_email                = 'EDIT ME: EG admin@example.org'
  $admin_password             = 'CHANGEME'
  $cinder_db_password         = 'CHANGEME'
  $cinder_user_password       = 'CHANGEME'
  $fixed_network_range        = 'EDIT ME: EG 10.100.10.0/24'
  $floating_network_range     = 'EDIT ME: EG 8.21.28.128/25'
  $glance_db_password         = 'CHANGEME'
  $glance_user_password       = 'CHANGEME'
  $horizon_secret_key         = 'CHANGEME'
  $keystone_admin_token       = 'CHANGEME'
  $keystone_db_password       = 'CHANGEME'
  $mysql_root_password        = 'CHANGEME'
  $nova_db_password           = 'CHANGEME'
  $nova_user_password         = 'CHANGEME'
  $pacemaker_priv_floating_ip = 'EDIT ME PRIV: EG 8.21.28.128/25'
  $pacemaker_pub_floating_ip  = 'EDIT ME PUBL: EG 10.100.10.0/24'
  $private_interface          = 'EDIT ME: em1'
  $public_interface           = 'EDIT ME: em2'
  $verbose                    = 'true'
}
